name: habit_tracker
description: Personal habit tracker app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2

  uuid: ^4.3.3
  # UI
  cupertino_icons: ^1.0.6

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Notifications
  flutter_local_notifications: ^17.0.0

  # PDF Export
  pdf: ^3.10.7
  path_provider: ^2.1.2

  # Charts
  fl_chart: ^0.66.0

  # Calendar / Heatmap
  table_calendar: ^3.0.9

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

  assets:
    - assets/
